title:              Henrique Reichert
email:              henrique@caravela.biz
description:        Conteúdos colaborativos de análise de dados em R
author:             Henrique Reichert
baseurl:            ""
url:                "https://henriquert.github.io"

# Social Profiles
twitter_username:   henrique_rt
github_username:    henriquert
facebook_username:  
instagram_username:  henrique_rt
linkedin_username: henrique-reichert-76508b107

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
